import {
    LayoutDashboard,
    ShoppingCart,
    Utensils,
    Armchair,
    CalendarDays,
    ReceiptText,
    Package,
    Users,
    BarChart3,
    TrendingUp,
    Wallet,
    Settings,
    Clock,
    ShieldCheck,
    MessageCircle,
} from 'lucide-react'

export const NAV = [
    {
        path: '/app',
        label: 'Dashboard',
        icon: LayoutDashboard,
        end: true,
        permission: 'DASHBOARD.READ',
    },
    {
        path: '/app/pos',
        label: 'POS',
        icon: ShoppingCart,
        permission: 'POS.READ',
    },
    {
        path: '/app/menu',
        label: 'Menu',
        icon: Utensils,
        permission: 'MENU.READ',
    },
    {
        path: '/app/tables',
        label: 'Tables',
        icon: Armchair,
        permission: 'POS.READ',
    },
    {
        path: '/app/reservations',
        label: 'Reservations',
        icon: CalendarDays,
        permission: 'POS.READ',
    },
    {
        path: '/app/invoices',
        label: 'Invoices',
        icon: ReceiptText,
        permission: 'INVOICES.READ',
    },
    {
        path: '/app/inventory',
        label: 'Inventory',
        icon: Package,
        permission: 'INVENTORY.READ',
    },
    {
        path: '/app/customers',
        label: 'Customers',
        icon: Users,
        permission: 'CUSTOMERS.READ',
    },
    {
        path: '/app/reports',
        label: 'Reports',
        icon: BarChart3,
        permission: 'REPORTS.READ',
    },
    {
        path: '/app/profit-loss',
        label: 'Profit & Loss',
        icon: TrendingUp,
        permission: 'PNL.READ',
    },
    {
        path: '/app/expenses',
        label: 'Expenses',
        icon: Wallet,
        permission: 'PAYROLL.READ',
    },
    {
        path: '/app/attendance',
        label: 'Attendance',
        icon: Clock,
        permission: 'ATTENDANCE.READ',
    },
    {
        path: '/app/staff',
        label: 'Staff',
        icon: Users,
        permission: 'STAFF.READ',
    },
    {
        path: '/app/payroll',
        label: 'Payroll',
        icon: Wallet,
        permission: 'PAYROLL.READ',
    },
    {
        path: '/app/user-permissions',
        label: 'Permissions',
        icon: ShieldCheck,
        permission: 'ROLES.READ',
    },
    {
        path: '/app/settings',
        label: 'Settings',
        icon: Settings,
        permission: 'SETTINGS.READ',
    },
]